server:
  port: 8080
  servlet:
    context-path: /v1/hrm

spring:
  application:
    name: hrm-backend

  datasource:
    url: jdbc:mysql://localhost:3306/hrm-database
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      pool-name: HikariConnectionPool

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        legacy_limit_handler: true

  jackson:
    serialization.write-dates-as-timestamps: false
    time-zone: UTC
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "thanhdatnguyen211103@gmail.com"
    password: "rtaffkwjzjjfnlpy"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  from-sender: thanhdatnguyen211103@gmail.com
  company: "Công ty giải pháp phần mềm TDSoftware"